enabled: true

handlers:
  # Light-framework cross-cutting concerns implemented in the microservice
  - com.networknt.exception.ExceptionHandler@exception
  - ch.madskills.metricsServer.handlers.FileHandler@fileHandler
  - ch.madskills.metricsServer.handlers.MetricsHandler@metricsHandler

chains:
  default:
    - exception
    - traceability
    - correlation
    - stateless
    - header
    - path
    - router

paths:
  - path: '/metrics/hardware'
    method: 'get'
    exec:
      - default
      - metricsHandler
  - path: '/metrics/files'
    method: 'get'
    exec:
      - default
      - fileHandler